#spring.application.name=services-registration
#server.port=8761
#means do not register this service
#eureka.client.register-with-eureka=false
#means do not fetch  this service
#ureka.client.fetch-registry=false

spring.application.name=services-registration
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

