spring.application.name=demo

# H2 Data base
#spring.h2.console.enabled =true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.dll-auto=create-drop
#spring.jpa.generate-ddl=true



#PostgreSQL
spring.datasource.url=jdbc:postgresql://Localhost:5432/jobapp
spring.datasource.username=sa
spring.datasource.password=123456
spring.jpa.datasource=POSTGRESQL
spring.jpa.show-sql=true
#spring.jpa.hibernate.dll-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop



















