spring.application.name=job-api
server.port=5081

# H2 Database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true


